services:
  - type: web
    name: stockpulse-backend
    env: java
    region: oregon
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
      - key: SERVER_PORT
        sync: false
        value: 8080
      - key: STOCK_API_BASE_URL
        value: https://api.freeapi.app/api/v1/public/stocks
    healthCheckPath: /actuator/health
